### ISSUE TITLE
Wundergraph -- similar db schema -> graphql schema generation idea

### ISSUE THREAD

**Issue by tantaman** [tantaman/aphrodite#16]
https://wundergraph.com/

**Comment by jensneuse** [comment]
I'm the founder of WunderGraph. It would be interesting to chat.

**Comment by tantaman** [comment]
@jensneuse - yeah, I'd love to.

Some background on myself for context on what I'm doing here but first a tldr:

> We can move large swaths of application concerns into the schema layer that describes the application's data model. Concerns ranging from generating storage layer schemas, creating a consistent query layer for that data, to determining what to expose to client facing APIs and how access to the data is controlled. Further, we can express all of these in a declarative way.

The longer version --

I worked at Meta/Facebook on problems ranging from trust & safety to security and privacy.

The high level problem we needed to solve in all of those cases was:

> How do we ensure that any time a new product is built, it is automatically integrated with our [abuse protection/privacy/compliance] systems?

And the solution always came back to schematization. We added declarative primitives to our schema layer so product devs could describe their data in a way that all the other systems at Facebook could understand. This allowed us to:
- Enforce [correct deletion of data](https://engineering.fb.com/2020/08/12/security/delf/) when users requested deletion
- Support ["download your information"](https://www.facebook.com/help/212802592074644)
- [Render the data in human review tooling](https://about.fb.com/news/2020/08/how-we-review-content/)
- Extract features from new products for ML
- Classify clusters of content
- Enforce rate limits on actions
- Enforce [purpose limitation](https://uk.practicallaw.thomsonreuters.com/Glossary/UKPracticalLaw/I1a11102e5ea511e89bf199c0ee06c731?transitionType=Default&contextData=(sc.Default)&firstPage=true#:~:text=A%20principle%20that%20data%20collected,specific%20definition%20in%20certain%20jurisdictions.)
- Support reactivity (i.e., GraphQL subscriptions) with little code (similar to Wundergraph)
- and on and on

---

Fast forward to May 2022, I departed Meta/Facebook to pursue my own interests. I'm still looking for the best place to focus my efforts but it does look like there might be something missing in regards to a schema layer like the one we had @ Meta that can get rid of much of the boilerplate plumbing and integration work.

Plumbing and integration work like those above (which, admittedly, are probably less of a concern for a small business) but also generating DB Schemas, GraphQL schemas, storage migrations, etc.

Now most of the latter seem to be covered by Prisma and Wundergraph.

Some departures / opportunities that I see, however:

# Encoding privacy policies into the schema.

My problem with API level and controller level privacy is that it they're one mistake away from causing security and privacy holes. I.e., someone adds a new controller and forgets to check x/y/z authorization.

Colocating privacy concerns with the data ensures that the data is always accessed correctly, no matter what API endpoint or controller someone used to get to it. This is very very important in a GraphQL world. Adding it to the schema definition is also more transparent and robust than relying on a specific implementation like Postgres RLS.

# Language agnostic

Ideally the schema you write can generate models in JS/Java/Rust/Python/... and they'd work the same in each language. I.e., enforce consistent privacy and invariants on mutations.

This is definitely a big company problem (e.g., Meta trying to integrate all their acquisitions and retain existing privacy rules). Not sure how big of a problem this is for smaller companies.

# Edges between data stores

I need to do more research on Prisma still but it is unclear to me if it is possible to do something like the following in Prisma:

```
objectInSQL.queryEdgeToObjectInLevelDB().queryEdgeToObjectInCassandra().queryEdgeToObjectInRedis()...
```

this was something we did pretty often @ Meta. Pivoting from one storage layer (e.g., Messenger) to another (e.g., Instagram backend) in single and consistent language.

The schema layer let you create edges between schemas, and follow those edges, even if they crossed storage engines. This is really the same problem as crossing shards so actually not that crazy or hard.

Some brief words on how that works [here](https://gist.github.com/tantaman/bd928ef93619e73365b07899da282996#aside---traversing-across-storage-backends).

# Define mutations in the schema

Looks like Wundergraph has users define mutations in GraphQL. I think I'd probably go the route of expressing mutations in the same schema that is used to express the data model.

**Comment by tantaman** [comment]
Lmk if you're still interested in chatting. I can make time pretty much any week day.

Given I've recently re-entered the real world / left Facebook infra behind, I'm spending most of my time getting up to speed on things like hasura, the-guild.dev, wundergraph, prisma, redwoodjs, nextjs, etc. etc. to make sure these ideas are needed or not being solved better elsewhere.

**Comment by tantaman** [comment]
I think Aphrodite is going in a pretty significantly different direction. **Draft** plan of where we're going is here:
https://aphrodite.sh/ (the doc needs another week of work but it gets the main _technical_ points across)
